"""Check the idempotent formula against published values, and fix the priority.

Dolinka & East, "Idempotent generation in the endomorphism monoid of a uniform
partition", Comm. Algebra 44 (2016) 5179-5198 (arXiv:1407.3312), enumerate the
idempotents of T(X,P) for a UNIFORM partition and print a table of values. Our
note derived an idempotent count independently, for partial maps with
block-saturated domain. Restricting that to full domain must reproduce their
table, or one of the two is wrong.

Their Table 3, |E(T(X,P))| for m blocks of size n, as printed in the paper:

     m\n :   1        2         3           4              5
      4  :  41     2073    401560   233777121   349447639616
      5  : 196    26553  21212980 74070192121 977698734939376
"""

import sys
import itertools
from math import comb

sys.stdout.reconfigure(encoding="utf-8")


def idem_total(p):
    """Idempotents of T(X,P), from our own derivation, full domain.

    Choose the fixed-point set S_i inside each block. A block carrying fixed
    points must map into itself (its fixed points go to themselves); a
    fixed-point-free block may target any block that carries some.
    """
    m = len(p)
    total = 0
    for s in itertools.product(*[range(n + 1) for n in p]):
        carriers = [j for j in range(m) if s[j] >= 1]
        if not carriers:
            continue                       # an idempotent needs a fixed point
        ways = 1
        for i in range(m):
            ways *= comb(p[i], s[i])
        for i in range(m):
            if s[i] >= 1:
                ways *= s[i] ** (p[i] - s[i])
            else:
                ways *= sum(s[j] ** p[i] for j in carriers)
        total += ways
    return total


def brute_idem_total(p):
    """Independent brute force: enumerate T(X,P) and keep f with f*f == f."""
    n = sum(p)
    blocks, pts, start = [], [], 0
    for sz in p:
        blocks.append(list(range(start, start + sz)))
        pts += [len(blocks) - 1] * sz
        start += sz
    c = 0
    for f in itertools.product(range(n), repeat=n):
        if any(len({pts[f[x]] for x in B}) > 1 for B in blocks):
            continue
        if all(f[f[x]] == f[x] for x in range(n)):
            c += 1
    return c


print("=" * 74)
print("1. Our formula vs BRUTE FORCE (small, both uniform and non-uniform)")
print("=" * 74)
ok = True
for p in [(1, 1), (2, 1), (2, 2), (3, 1), (1, 1, 1), (2, 1, 1), (3, 2), (2, 2, 1)]:
    a, b = idem_total(p), brute_idem_total(p)
    ok &= a == b
    print(f"  {str(p):<12} formula {a:>8}   brute {b:>8}   "
          f"{'ok' if a == b else 'MISMATCH'}")
print(f"  all agree: {ok}")

print()
print("=" * 74)
print("2. Our formula vs DOLINKA-EAST's PUBLISHED TABLE 3 (uniform only)")
print("=" * 74)
published = {
    (4, 1): 41, (4, 2): 2073, (4, 3): 401560,
    (4, 4): 233777121, (4, 5): 349447639616,
    (5, 1): 196, (5, 2): 26553, (5, 3): 21212980,
    (5, 4): 74070192121, (5, 5): 977698734939376,
}
allok = True
print(f"  {'m':>2} {'n':>2} {'published':>18} {'ours':>18}   match")
for (m, n), val in sorted(published.items()):
    ours = idem_total((n,) * m)
    good = ours == val
    allok &= good
    print(f"  {m:>2} {n:>2} {val:>18,} {ours:>18,}   "
          f"{'ok' if good else 'MISMATCH'}")
print()
print(f"  ALL PUBLISHED VALUES REPRODUCED: {allok}")

print()
print("=" * 74)
print("3. What this settles")
print("=" * 74)
print("""  The uniform idempotent count IS published (Dolinka-East 2016). Our note
  must cite it rather than present the uniform case as unexamined.

  The non-uniform idempotent COUNT is still not found. The sequel
  - Dolinka, East & Mitchell, Bull. Aust. Math. Soc. 93 (2016) 73-91,
    arXiv:1504.02520, "Idempotent rank in the endomorphism monoid of a
    NON-uniform partition" -
  computes the rank and idempotent rank of the subsemigroup GENERATED by the
  idempotents. That is a different invariant from how many there are.

  So the pattern already noted holds here too, exactly: where the literature
  goes non-uniform it computes RANK, and where it computes ORDER it fixes the
  partition uniform. The extremal question needs order as a function of shape,
  which is the one combination nobody published.""")

print()
print("=" * 74)
print("4. Does the extremal law hold for idempotents? (still only finite test)")
print("=" * 74)


def parts(n, m, top=None):
    if top is None:
        top = n
    if m == 1:
        if 1 <= n <= top:
            yield (n,)
        return
    for f in range(min(top, n - m + 1), 0, -1):
        for r in parts(n - f, m - 1, f):
            yield (f,) + r


def exchanges(p):
    out = set()
    for i in range(len(p)):
        for j in range(len(p)):
            if i == j:
                continue
            a, b = p[i], p[j]
            if b >= 2 and a >= b:
                q = list(p)
                q[i], q[j] = a + 1, b - 1
                out.add(tuple(sorted(q, reverse=True)))
    return out


tot = bad = 0
first = None
for n in range(2, 15):
    for m in range(1, n + 1):
        for p in parts(n, m):
            vp = idem_total(p)
            for q in exchanges(p):
                tot += 1
                if idem_total(q) <= vp:
                    bad += 1
                    if first is None:
                        first = (p, q)
print(f"  exchanges tested {tot:,}   failures {bad}")
print(f"  FIRST FAILURE {first}" if first else
      "  holds in every case tested, n <= 14. Still a conjecture: the count")
print("  does not factor over blocks, so the log-convexity proof has nothing")
print("  to act on. No mechanism is claimed.")
